### ISSUE TITLE
Custom root data folder doesn't play nicely in TinyMCE

### ISSUE THREAD

**Issue by leighelse** [silverstripe/silverstripe-dms#60] opened 2015-03-08 21:46 UTC
We want to deploy within CWP, where we need to store DMS content in a subfolder under assets. Setting up a custom sub-folder is straightforward, and documents are successfully uploaded; but this breaks TinyMCE integration. The custom document option is still present when inserting a link, but no folders or documents are displayed for selection once that option is selected.

I'm going to fork this and take a look, but I thought it would be sensible to document the issue.

Unfortunately the configuration of CWP sites precludes putting DMS content outside assets.

**Comment by robbieaverill** [comment] 2017-05-01 05:17
Hi @leighelse - we'll be looking at this as part of #98 with CWP as a use-case. Did you get anywhere with it yourself?

**Comment by robbieaverill** [comment] 2017-05-01 05:18
Closing as duplicate of #98 - please follow progress on this issue there.

**Closed by robbieaverill** 2017-05-01 05:18 UTC

**Comment by leighelse** [comment] 2017-05-01 07:26
I believe we crafted a fix. I've only recently returned to govt.nz after a couple of years away. I'll have to check where the bodies are buried and see what  was done.

**Comment by robbieaverill** [comment] 2017-05-01 08:06
Great, thanks!
